"use client";

const money = (value) => `৳${Number(value || 0).toLocaleString("en-US")}`;

export default function CartDrawer({ open, setOpen, cart, count, subtotal, delivery, changeQuantity, form, setForm, done, whatsapp, error, busy, onOrder }) {
  return <>
    <button className={`drawer-scrim ${open ? "is-visible" : ""}`} aria-label="Close cart" tabIndex={open ? 0 : -1} onClick={() => setOpen(false)} />
    <aside className={`cart-drawer ${open ? "is-open" : ""}`} aria-label="Shopping cart" aria-hidden={!open} inert={!open ? "" : undefined}>
      <div className="drawer-heading"><div><span className="eyebrow">Your selection</span><h2>Your bag <span>({count})</span></h2></div><button className="icon-button" onClick={() => setOpen(false)} aria-label="Close cart">×</button></div>
      <div className="drawer-content">{count ? <div className="cart-lines">{cart.map((item, index) => <div className="cart-line" key={`${item.id}-${item.size}`}><span className="cart-swatch" style={{ background: item.color || "var(--marigold)" }} /><div className="cart-line-name"><b>{item.name}</b><small>Size {item.size} · {money(item.price)}</small></div><div className="quantity-control"><button onClick={() => changeQuantity(index, -1)} aria-label={`Remove one ${item.name}`}>−</button><span>{item.qty}</span><button onClick={() => changeQuantity(index, 1)} aria-label={`Add one ${item.name}`}>+</button></div></div>)}</div> : done ? <div className="order-success"><span className="success-mark">✓</span><span className="eyebrow">Thank you</span><h3>Order placed</h3><p>Your order <b>{done.no}</b> ({money(done.total)}) is received. We will call you soon to confirm.</p>{whatsapp && <a className="button button-navy" target="_blank" rel="noreferrer" href={`https://wa.me/${whatsapp}?text=${encodeURIComponent(done.msg)}`}>Also send details on WhatsApp</a>}<button className="text-link" onClick={() => { setOpen(false); }}>Continue shopping</button></div> : <p className="empty-cart">Your bag is waiting for something lovely.</p>}</div>
      {count > 0 && <div className="checkout"><div className="checkout-row"><span>Subtotal</span><b>{money(subtotal)}</b></div><label>Delivery area<select value={form.area} onChange={(event) => setForm({ ...form, area: event.target.value })}><option value="dhaka">Inside Dhaka · ৳60</option><option value="outside">Outside Dhaka · ৳120</option></select></label><div className="checkout-row"><span>Delivery</span><b>{delivery ? money(delivery) : "Free"}</b></div><div className="checkout-row total-row"><span>Total</span><b>{money(subtotal + delivery)}</b></div><p className="checkout-note">Free delivery on orders over ৳3,000.</p>
        <input placeholder="Full name" autoComplete="name" aria-label="Full name" value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} /><input placeholder="Phone number" inputMode="tel" autoComplete="tel" aria-label="Phone number" value={form.phone} onChange={(event) => setForm({ ...form, phone: event.target.value })} /><textarea rows="2" placeholder="Full delivery address" aria-label="Full delivery address" value={form.address} onChange={(event) => setForm({ ...form, address: event.target.value })} />
        <label>Payment method<select value={form.payment} onChange={(event) => setForm({ ...form, payment: event.target.value })}><option value="cod">Cash on delivery</option><option value="bkash">Pay with bKash</option><option value="nagad">Pay with Nagad</option></select></label>
        {form.payment !== "cod" && <div className="payment-instructions">Send {money(subtotal + delivery)} by Send Money to <b>{form.payment === "bkash" ? process.env.NEXT_PUBLIC_BKASH_NUMBER : process.env.NEXT_PUBLIC_NAGAD_NUMBER}</b>, then enter the TrxID from the confirmation message.<input placeholder="Transaction ID (TrxID)" aria-label="Transaction ID" value={form.trx_id} onChange={(event) => setForm({ ...form, trx_id: event.target.value })} /></div>}
        <p className="form-error" role="alert">{error}</p><button className="button button-navy checkout-button" disabled={busy} onClick={onOrder}>{busy ? "Placing order…" : "Place order"}</button>
      </div>}
    </aside>
  </>;
}